### ISSUE TITLE
Video skips the first few seconds when starting a new video

### ISSUE THREAD

**Issue by PhaxeNor** [synergiance/SynMediaPlayer#3]

**Comment by synergiance** [comment]
In order to solve this, I think I'll need to have the current owner of the video player mark the video to start once 75% of the people in the world have the video loaded.  This can be done by creating an int that resets to zero on beginning video load, then having each client send a message to the owner to indicate when they're ready.  The current owner decides to play the video once this value reaches 75% of the number of people with the video player active.

Note: I'll need to be able to track how many people have their video player enabled.  I'll also need to not send the ready message when the video player needs to double load the video.

**Comment by synergiance** [comment]
This seems to be resolved with commit 0553b84d0ad55acefa7052c735025a211e6ad93f which adds more structure about when a video will play or not.
